- src/main/webapp/lecture-list.html
- src/main/webapp/lecture-view.html
> Add js and html files for lecture view and list

- src/main/java/com/googleinterns/zoomtube/data/Lecture.java
- src/main/java/com/googleinterns/zoomtube/servlets/LectureServlet.java
This pull request adds support for redirecting to new lecture page after user enters a new lecture.
> Added URL builder to LectureServlet.java

- .eslintrc.json
- src/main/java/com/googleinterns/zoomtube/data/Comment.java
- src/main/java/com/googleinterns/zoomtube/servlets/DiscussionServlet.java
- src/main/webapp/discussion.js
- src/main/webapp/lecture-view.html
- src/main/webapp/view.js
UI obviously needs some work:
https://screenshot.googleplex.com/oTNmD12jiF5
> Add the ability to reply to comments

- pom.xml
- src/main/java/com/googleinterns/zoomtube/servlets/TranscriptServlet.java
- src/main/webapp/transcript.js
Retrieves and parses the XML with the transcript upon fetching /transcript. 
Transcript (Start time, duration, and text) as printed in the console: https://screenshot.googleplex.com/SNdLcSTDsAN.png
> Retrieve and Parse XML for hardcoded transcript text and timestamp.

- .github/workflows/lint.yml
- makefile
- pom.xml
- src/main/java/com/googleinterns/zoomtube/data/AuthenticationStatus.java
- src/main/java/com/googleinterns/zoomtube/data/Comment.java
- src/main/java/com/googleinterns/zoomtube/servlets/AuthenticationServlet.java
- src/main/java/com/googleinterns/zoomtube/servlets/DiscussionServlet.java
- src/main/webapp/discussion.js
- src/main/webapp/lecture-view.html
- src/main/webapp/view.js
- src/test/java/com/googleinterns/zoomtube/servlets/AuthenticationServletTest.java
Displays a login/logout link, as well as the current user's email.  All comments now display the author's email.
Screenshot:  https://screenshot.googleplex.com/Lhgcs7UiJRB
> Add authentication for posting comments

- README.md
- index.yaml
- pom.xml
To deploy in the future:
```
gcloud config set project zoomtube-step-2020
gcloud datastore indexes create index.yaml  # check the console and wait for indexing to finish
make deploy
```
> Update project config to deploy on GCP; add link in README

- src/main/java/com/googleinterns/zoomtube/servlets/LectureServlet.java
- src/test/java/com/googleinterns/zoomtube/servlets/LectureServletTest.java
We renamed the file and forgot to change the name of the file in the redirect link.
> Fix redirect error in master

- src/main/webapp/auth.js
- src/main/webapp/discussion.js
- src/main/webapp/view.html
This way the code can be reused on multiple pages.
Next steps:
- Include on every page that needs auth info
- Automatically set logout/login button href and text after fetch (using the same `id` on every page?)
> Move authentication code to auth.js

- src/main/java/com/googleinterns/zoomtube/servlets/TranscriptServlet.java
- src/test/java/com/googleinterns/zoomtube/servlets/TranscriptServletTest.java
Eliminates the need for two inits in `TranscriptServlet.java`
> Removes dual inits in TranscriptServlet

- .githooks/pre-commit
- .githooks/pre-push
Re: our discussion today, this changes the pre-commit hook to a pre-push hook.  We also no longer build/run tests very time.
In addition, this updates the linter to check the correct directories for CSS
> Change hook to pre-push and don't run tests

- src/main/webapp/view/transcript/transcript.js
Two functions were created to apply and remove the bold font weight on a transcript line depending on whether it is the current line.
First transcript line is bolded: https://screenshot.googleplex.com/8X4UwsNjrWu.png
> Add and Remove Bold for the Current Transcript Line.

- src/main/webapp/global.css
- src/main/webapp/landing-page.css
This pr fixes the margin bottom on the header and makes the style global.
Screenshots: 
Before: https://screenshot.googleplex.com/nYBt09yFOTc.png
After: https://screenshot.googleplex.com/9g2SvvDy4wD.png
> Fixed header margin and font weight

- src/main/webapp/view/index.html
In a subsequent pull request, the transcript class will be updated to use the slots.
> Add template for transcript line.

- src/main/webapp/global.css
- src/main/webapp/index.html
- src/main/webapp/lectures/index.html
Closes: #157 
Note: This does not change the header in `webapp/view/index.html` because that header is automatically replaced with the Lecture's name.
> Make ZoomTube link to About page

- src/main/webapp/global.css
- src/main/webapp/index.html
- src/main/webapp/lectures/index.html
- src/main/webapp/view/view.js
This pr adds the lecture name to the header of the view page.
> Added lecture name to the header of view page

- src/main/java/com/googleinterns/zoomtube/servlets/TranscriptServlet.java
- src/main/webapp/view/transcript/transcript.js
- src/main/webapp/view/view.js
- src/test/java/com/googleinterns/zoomtube/servlets/TranscriptServletTest.java
Last PR for #178 
This one is short--only one parameter is used.
> Require parameters in TranscriptServlet

- src/main/webapp/lectures/lectures.js
- src/main/webapp/synchronizer.js
- src/main/webapp/timestamps.js
- src/main/webapp/view/discussion/discussion.js
- src/main/webapp/view/transcript/transcript.js
- src/main/webapp/view/video/video.js
- src/main/webapp/view/view.js
> Replace javascript @code with backticks

- src/main/java/com/googleinterns/zoomtube/transcriptParser/TranscriptParser.java
- src/main/webapp/view/transcript/transcript.js
> Update TranscriptParser to use URLBuilder

- src/main/webapp/view/discussion/discussion-area.js
Also slightly cleans up the `postNewComment` code
Closes: #329
> Clear the new comment textarea on post

- src/main/webapp/global.css
- src/main/webapp/scroll-container.js
Closes: #330 
(see issue for more details)
> Add smooth scrolling to scroll containers

- src/main/webapp/timestamp-util.js
- src/main/webapp/timestamps.js
- src/main/webapp/view/discussion/discussion-area.js
- src/main/webapp/view/discussion/discussion-comment.js
- src/main/webapp/view/transcript/transcript.js
- src/main/webapp/view/video/video.js
This pr makes `timestamp.js` into `timestamp-util.js` a static util class.
> Refactors timestamp.js to a class

- src/main/webapp/view/discussion/discussion-area.js
- src/main/webapp/view/discussion/discussion-comment.js
I forgot to change some client code when making the TranscriptLine an Optional in Comment. This fixes errors on master and makes those requests work.
Closes: #325
> Fix adding transcript line to comment post request

- src/main/webapp/view/index.html
- src/main/webapp/view/lecture-view.css
- src/main/webapp/view/video/video.js
This pr fixes the fixed size of the video player. It is now dynamically sized and adjusts to screen size.
> Made video player dynamically adjust size

- src/main/webapp/view/discussion/discussion-area.js
- src/main/webapp/view/lecture-view.js
This should be the last pull request for comment indicator.
> Call incrementCommentIndicatorAt() in DiscussionArea.
